<img src="https://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

# Reinforcement Learning for Finance

**Chapter 09 &mdash; Optimal Execution**

&copy; Dr. Yves J. Hilpisch

<a href="https://tpq.io" target="_blank">https://tpq.io</a> | <a href="https://twitter.com/dyjh" target="_blank">@dyjh</a> | <a href="mailto:team@tpq.io">team@tpq.io</a>

## Model Implementation

In [1]:
import math
import random
import numpy as np
import pandas as pd
from pylab import plt, mpl
import torch
import torch.nn as nn
import torch.optim as optim
from dqlagent_pytorch import DQLAgent, QNetwork, device

In [2]:
plt.style.use('seaborn-v0_8')
mpl.rcParams['figure.dpi'] = 300
mpl.rcParams['savefig.dpi'] = 300
mpl.rcParams['font.family'] = 'serif'
np.set_printoptions(suppress=True)

In [3]:
class AlmgrenChriss:
    def __init__(self, T, N, S0, sigma, X, gamma, eta, lamb):
        self.T = T              
        self.N = N           
        self.dt = T / N
        self.S0 = S0
        self.sigma = sigma
        self.X = X
        self.gamma = gamma
        self.eta = eta
        self.lamb = lamb

In [4]:
class AlmgrenChriss(AlmgrenChriss):
    def optimal_execution(self):
        kappa = np.sqrt(self.lamb * self.sigma ** 2 / self.eta)
        t = np.linspace(0, self.T, self.N + 1)
        xt_sum = (self.X * np.sinh(kappa * (self.T - t)) /
                  np.sinh(kappa * self.T))
        xt = -np.diff(xt_sum, prepend=0)
        xt[0] = 0
        return t, xt

In [5]:
T = 10
N = 10
S0 = 1
sigma = 0.15
X = 1
gamma = 0.1
eta = 0.1
lamb_high = 0.2
lamb_low = 0.0001

In [6]:
ac = AlmgrenChriss(T, N, S0, sigma, X, gamma, eta, lamb_high)

In [7]:
t, xth = ac.optimal_execution()

In [8]:
t

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
xth.round(3)

array([0.   , 0.197, 0.161, 0.132, 0.109, 0.091, 0.077, 0.067, 0.059,
       0.054, 0.052])

In [10]:
ac.lamb = lamb_low

In [11]:
t, xtl = ac.optimal_execution()
xtl.round(3)

array([0. , 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [12]:
#plt.plot(t, ac.X - xth.cumsum(), 'r', lw=1, label='high $\\lambda$ (position)')
#plt.plot(t, xth, 'rs', markersize=4, label='high $\\lambda$ (trade)')
#plt.plot(t, ac.X- xtl.cumsum(), 'b--', lw=1, label='low $\\lambda$ (position)')
#plt.plot(t, xtl, 'bo', markersize=4, label='low $\\lambda$ (trade)')
#.xlabel('trading day')
#plt.ylabel('shares (normalized to 1)')
#plt.legend();

In [13]:
from numpy.random import default_rng

In [14]:
class AlmgrenChriss(AlmgrenChriss):
    def simulate_stock_price(self, xt, seed=None):
        rng = default_rng(seed=seed)
        S = np.zeros(self.N + 1)
        S[0] = self.S0
        P = np.zeros(self.N + 1)
        P[0] = self.S0
        for t in range(1, self.N + 1):
            dZ = rng.normal(0, np.sqrt(self.dt))
            S[t] = S[t - 1] + sigma * dZ
            P[t] = S[t] - self.gamma * xt[:t + 1].sum()
        return S, P

In [15]:
ac = AlmgrenChriss(T, N, S0, sigma, X, gamma, eta, lamb_high)

In [16]:
t, xth = ac.optimal_execution()

In [17]:
xth.round(2)

array([0.  , 0.2 , 0.16, 0.13, 0.11, 0.09, 0.08, 0.07, 0.06, 0.05, 0.05])

In [18]:
seed = 250

In [19]:
S, Ph = ac.simulate_stock_price(xth, seed=seed)

In [20]:
ac.lamb = lamb_low

In [21]:
t, xtl = ac.optimal_execution()

In [22]:
xtl.round(2)

array([0. , 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [23]:
S, Pl = ac.simulate_stock_price(xtl, seed=seed)

In [24]:
#plt.plot(t, S, 'b', lw=1, label='simulated stock price path')
#plt.plot(t, Ph, 'r--', lw=1, label='adjusted path (high $\\lambda$)')
#plt.plot(t, Pl, 'g:', lw=1, label='adjusted path (low $\\lambda$)')
#plt.xlabel('trading day')
#plt.ylabel('stock price (normalized to 1)')
#plt.legend();

In [25]:
class AlmgrenChriss(AlmgrenChriss):
    def calculate_costs(self, xt):
        temporary_cost = np.sum(self.eta *
                    (xt / self.dt) ** 2 * self.dt)
        permanent_cost = np.sum(self.gamma * np.cumsum(xt) * xt)
        execution_risk = self.lamb * self.sigma ** 2 * np.sum(
            (np.cumsum(xt[::-1])[::-1] / self.dt) ** 2 * self.dt)
        TEC = temporary_cost + permanent_cost + execution_risk
        return temporary_cost, permanent_cost, execution_risk, TEC

In [26]:
ac = AlmgrenChriss(T, N, S0, sigma, X, gamma, eta, lamb_high)

In [27]:
t, xth = ac.optimal_execution()

In [28]:
tc, pc, er, TEC = ac.calculate_costs(xth)

In [29]:
print(f'lambda = {ac.lamb}')
print(f'temporary cost = {tc:7.4f}')
print(f'permanent cost = {pc:7.4f}')
print(f'execution risk = {er:7.4f}')
print(f'total ex. cost = {TEC:7.4f}')

lambda = 0.2
temporary cost =  0.0122
permanent cost =  0.0561
execution risk =  0.0165
total ex. cost =  0.0848


In [30]:
ac.lamb = lamb_low

In [31]:
t, xtl = ac.optimal_execution()

In [32]:
tc, pc, er, TEC = ac.calculate_costs(xtl)

In [33]:
print(f'lambda = {ac.lamb}')
print(f'temporary cost = {tc:7.4f}')
print(f'permanent cost = {pc:7.4f}')
print(f'execution risk = {er:7.4f}')
print(f'total ex. cost = {TEC:7.4f}')

lambda = 0.0001
temporary cost =  0.0100
permanent cost =  0.0550
execution risk =  0.0000
total ex. cost =  0.0650


## Execution Environment

In [34]:
class action_space:
    n = 1

In [35]:
class Execution:
    def __init__(self, T, N, sigma, X, gamma, eta, lamb):
        self.T = T              
        self.N = N           
        self.dt = T / N
        self.sigma = sigma
        self.X = X
        self.gamma = gamma
        self.eta = eta
        self.lamb = lamb
        self.episode = 0
        self.action_space = action_space()

In [36]:
class Execution(Execution):
    def _get_state(self):
        s = np.array([self.X_,
                    self.bar / self.N])
        state = np.hstack((self.xt, s))
        return state, {}
    def reset(self):
        self.bar = 0
        self.treward = 0
        self.episode += 1
        self.X_ = self.X
        self.xt = np.zeros(self.N + 1)
        self.tec = pd.DataFrame(
            {'pc': 0, 'tc': 0, 'er': 0}, index=[0])
        return self._get_state()

In [37]:
class Execution(Execution):
    def step(self, action):
        self.bar += 1
        self.xt[self.bar] = action
        self.X_ -= action
        pc = np.sum(self.gamma *
                np.cumsum(self.xt) * self.xt)
        tc = np.sum(self.eta *
                (self.xt / self.dt) ** 2 * self.dt)
        er = self.lamb * self.sigma ** 2 * np.sum(
            (np.cumsum(self.xt[::-1])[::-1] / self.dt) ** 2
            * self.dt)
        df = pd.DataFrame({'pc': tc, 'tc': pc, 'er': er},
                          index=[0])
        self.tec = pd.concat((self.tec, df))
        cost = self.tec.diff().fillna(0).iloc[-1]
        tec = cost.sum()
        self.state, _ = self._get_state()
        pen = 0
        if self.bar < self.N:
            if self.X_ <= 0.0001:
                done = True
            else:
                done = False
        elif self.bar == self.N:
            pen = abs(self.X_) * 10
            done = True
        return self.state, -(tec + pen), done, False, {}

In [38]:
execution = Execution(T, N, sigma, X, gamma, eta, lamb_low)

In [39]:
execution.reset()
execution.step(1.0)

(array([0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1]),
 -0.2000045,
 True,
 False,
 {})

In [40]:
execution.reset()

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]), {})

In [41]:
execution.step(0.5)

(array([0. , 0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5, 0.1]),
 -0.050001125,
 False,
 False,
 {})

In [42]:
execution.step(0.5)

(array([0. , 0.5, 0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.2]),
 -0.0750039375,
 True,
 False,
 {})

In [43]:
execution.reset()
cost = list()
for i in range(10):
    cost.append(execution.step(0.1)[1])
print(f'TEC = {sum(cost):.3f}')

TEC = -0.065


In [44]:
execution = Execution(T, N, sigma, X, gamma, eta, lamb_low)

In [45]:
rng = default_rng(seed=100)

In [46]:
def gen_rn():
    alpha = np.ones(N)
    rn = rng.dirichlet(alpha)
    rn = np.insert(rn, 0, 0)
    return rn

In [47]:
rn = gen_rn()
rn

array([0.        , 0.15895546, 0.12542041, 0.07457818, 0.00209012,
       0.08708588, 0.02557811, 0.05065022, 0.23502973, 0.16044992,
       0.08016197])

In [48]:
rn.sum()

1.0000000000000002

In [49]:
def execute_trades():
    for _ in range(5):
        execution.reset()
        rn = gen_rn()
        for i in range(1, 11):
            execution.step(rn[i])
        tec = execution.tec.iloc[-1].sum()
        print(f'TEC = {tec:.3f}')

In [50]:
execute_trades()

TEC = 0.072
TEC = 0.078
TEC = 0.081
TEC = 0.071
TEC = 0.099


In [51]:
execution = Execution(T, N, sigma, X, gamma, eta, lamb_high)

In [52]:
execute_trades()

TEC = 0.105
TEC = 0.103
TEC = 0.097
TEC = 0.097
TEC = 0.093


In [53]:
from dqlagent_pytorch import *

In [54]:
random.seed(100)
np.random.seed(100)
torch.manual_seed(100)

In [55]:
lr = 0.0001

In [56]:
class ExecutionAgent(DQLAgent):
    def __init__(self, symbol, feature, n_features, env, hu=24, lr=0.0001, rng='equal'):
        super().__init__(symbol, feature, n_features, env, hu, lr)
        self.eta = 1.0
        self.rng = rng
        self.episodes = 0
        self._generate_rn()
        # Actor-Critic networks
        self.actor = QNetwork(self.n_features, 1, hu).to(device)
        self.critic = QNetwork(self.n_features, 1, hu).to(device)
        self.act_opt = optim.Adam(self.actor.parameters(), lr=lr)
        self.crit_opt = optim.Adam(self.critic.parameters(), lr=lr)
        self.loss_fn = nn.MSELoss()

In [57]:
class ExecutionAgent(ExecutionAgent):
    def _generate_rn(self):
        # Dirichlet random mixture for execution weights
        from numpy.random import default_rng
        generator = default_rng()
        if self.rng == 'equal':
            alpha = np.ones(self.env.N)
        elif self.rng == 'decreasing':
            alpha = range(self.env.N, 0, -1)
        else:
            alpha = generator.random(self.env.N)
        rn = generator.dirichlet(alpha)
        self.rn = np.insert(rn, 0, 0)

In [58]:
class ExecutionAgent(ExecutionAgent):
    def _create_model(self, hu, lr, out_activation):
        # Not used in PyTorch implementation
        return None

In [59]:
class ExecutionAgent(ExecutionAgent):
    def act(self, state):
        if random.random() <= self.epsilon or self.episodes < 250:
            return min(self.rn[self.f], state[0, -2])
        state_t = torch.FloatTensor(state).unsqueeze(0).to(device)
        with torch.no_grad():
            action = float(torch.sigmoid(self.actor(state_t))[0,0].item())
        return action

In [60]:
class ExecutionAgent(ExecutionAgent):
    def replay(self):
        batch = random.sample(self.memory, self.batch_size)
        for state, action, next_state, reward, done in batch:
            state_t = torch.FloatTensor(state).unsqueeze(0).to(device)
            next_t = torch.FloatTensor(next_state).unsqueeze(0).to(device)
            # Critic update
            target = reward
            if not done:
                with torch.no_grad():
                    target += self.eta * self.critic(next_t)[0,0].item()
            pred_v = self.critic(state_t)[0,0]
            # ensure target dtype matches prediction
            target_v = pred_v.new_tensor(target)
            loss_v = self.loss_fn(pred_v, target_v)
            self.crit_opt.zero_grad()
            loss_v.backward()
            self.crit_opt.step()
            # Actor update
            pred_a = self.actor(state_t)[0,0]
            # ensure action target dtype matches prediction
            target_a = pred_a.new_tensor(action)
            loss_a = self.loss_fn(pred_a, target_a)
            self.act_opt.zero_grad()
            loss_a.backward()
            self.act_opt.step()
        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay
        self._generate_rn()

In [61]:
class ExecutionAgent(ExecutionAgent):
    def test(self, episodes, verbose=True):
        for e in range(1, episodes + 1):
            state, _ = self.env.reset()
            state = self._reshape(state)
            treward = 0
            for _ in range(1, self.env.N + 1):
                state_t = torch.FloatTensor(state).unsqueeze(0).to(device)
                with torch.no_grad():
                    action = float(self.actor(state_t)[0,0].item())
                state, reward, done, trunc, _ = self.env.step(action)
                state = self._reshape(state)
                treward += reward
                if done:
                    templ = f'total reward={treward:4.3f}'
                    if verbose:
                        print(templ)
                    break
            print(self.env.xt)

In [62]:
execution = Execution(T, N, sigma, X, gamma, eta, lamb_low)

In [63]:
executionagent = ExecutionAgent(None, feature=None,
                    n_features=execution.N + 3,
                    env=execution, hu=64, lr=0.0005,
                    rng='equal')

In [64]:
episodes = 1500

In [ ]:
%time executionagent.learn(episodes)

episode=   1 | treward= -0.075 | max= -0.075
episode=   2 | treward= -0.075 | max= -0.075
episode=   3 | treward= -0.075 | max= -0.075
episode=   4 | treward= -0.075 | max= -0.075
episode=   5 | treward= -0.070 | max= -0.070
episode=   6 | treward= -0.086 | max= -0.070
episode=   7 | treward= -0.080 | max= -0.070
episode=   8 | treward= -0.086 | max= -0.070
episode=   9 | treward= -0.098 | max= -0.070
episode=  10 | treward= -0.072 | max= -0.070
episode=  11 | treward= -0.083 | max= -0.070
episode=  12 | treward= -0.075 | max= -0.070
episode=  13 | treward= -0.070 | max= -0.070
episode=  14 | treward= -0.096 | max= -0.070
episode=  15 | treward= -0.087 | max= -0.070
episode=  16 | treward= -0.080 | max= -0.070
episode=  17 | treward= -0.071 | max= -0.070
episode=  18 | treward= -0.073 | max= -0.070
episode=  19 | treward= -0.086 | max= -0.070
episode=  20 | treward= -0.074 | max= -0.070
episode=  21 | treward= -0.076 | max= -0.070
episode=  22 | treward= -0.071 | max= -0.070
episode=  

In [66]:
executionagent.test(1)

total reward=-0.152
[0.         0.55724919 0.5441885  0.         0.         0.
 0.         0.         0.         0.         0.        ]


In [67]:
xtl_ = execution.xt
xtl_.sum()

1.1014376878738403

In [68]:
execution = Execution(T, N, sigma, X, gamma, eta, lamb_high)

In [69]:
executionagent = ExecutionAgent(None, feature=None,
                    n_features=execution.N + 3,
                    env=execution, hu=64, lr=0.0005,
                    rng='decreasing')

In [70]:
%time executionagent.learn(episodes)

episode=   1 | treward= -0.087 | max= -0.087
episode=   2 | treward= -0.087 | max= -0.087
episode=   3 | treward= -0.087 | max= -0.087
episode=   4 | treward= -0.087 | max= -0.087
episode=   5 | treward= -0.086 | max= -0.086
episode=   6 | treward= -0.088 | max= -0.086
episode=   7 | treward= -0.087 | max= -0.086
episode=   8 | treward= -0.088 | max= -0.086
episode=   9 | treward= -0.089 | max= -0.086
episode=  10 | treward= -0.087 | max= -0.086
episode=  11 | treward= -0.086 | max= -0.086
episode=  12 | treward= -0.091 | max= -0.086
episode=  13 | treward= -0.089 | max= -0.086
episode=  14 | treward= -0.088 | max= -0.086
episode=  15 | treward= -0.087 | max= -0.086
episode=  16 | treward= -0.086 | max= -0.086
episode=  17 | treward= -0.086 | max= -0.086
episode=  18 | treward= -0.088 | max= -0.086
episode=  19 | treward= -0.088 | max= -0.086
episode=  20 | treward= -0.086 | max= -0.086
episode=  21 | treward= -0.086 | max= -0.086
episode=  22 | treward= -0.086 | max= -0.086
episode=  

In [71]:
executionagent.test(1)

total reward=-0.202
[0.         0.60461438 0.6171056  0.         0.         0.
 0.         0.         0.         0.         0.        ]


In [72]:
xth_ = execution.xt
xth_.sum()

1.2217199802398682

In [73]:
#plt.plot(xtl[1:], 'b', lw=1, label='optimal for low $\lambda$')
#plt.plot(xtl_[1:], 'b:', lw=1, label='learned for low $\lambda$')
#plt.plot(xth[1:], 'r--', lw=1, label='optimal for high $\lambda$')
#plt.plot(xth_[1:], 'r-.', lw=1, label='learned for high $\lambda$')
#plt.xlabel('trading day')
#plt.ylabel('trade size')
#plt.legend();

<img src="https://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

<a href="https://tpq.io" target="_blank">https://tpq.io</a> | <a href="https://twitter.com/dyjh" target="_blank">@dyjh</a> | <a href="mailto:team@tpq.io">team@tpq.io</a>